<!--include header-->
<%- include('include/_header') %>
    <!--/include header-->

    <main id="site-main">
        <div id="container">
            <div class="box-nav d-flex justify-between">
                <a href="/add-user" class="border-shadow">   
                </a>
                <span class="text-gradient">New User <i class="fa-solid fa-user"></i></span>
                <button onclick="location.href='http://www.csac.ro/';">surprise</button>
                <button onclick=" location.href='https://scanstart.ro/';">surprise again</button>
                <button onclick="location.href='https://graffino.com/';">you allready know</button>
            </div>
            <form action="/method=" POST">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Genders</th>
                            <th>status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <%- include('include/_show') %>
                    </tbody>
                </table>
            </form>
        </div>
    </main>

    <!--include footer-->
    <%- include('include/_footer') %>
        <!--/include footer-->
        const axios = require('axios');

axios.get('http://localhost:3000/api/users')
  .then(response => {
    console.log('Data:', response.data);
  })
  .catch(error => {
    if (error.response) {
      // Server responded with a status other than 2xx
      console.error('Error Response:', error.response.status, error.response.data);
    } else if (error.request) {
      // Request was made but no response received
      console.error('Error Request:', error.request);
    } else {
      // Something happened in setting up the request
      console.error('Error Message:', error.message);
    }
    console.error('Error Config:', error.config);
  });
